# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: e2e CI

on:
  schedule:
  - cron: '0 4 * * *'  # Run daily at 4 AM
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
      - created

jobs:
  cypress-run:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Run Cypress
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
